grpc:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:shop
    driver-class-name: org.h2.Driver
    username: shop
    password: 123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
